name: Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEP_PATH: /requirements.txt

jobs:
  security_check:
    name: Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety

      - name: Check for Security Issues
        run: |
          source venv/bin/activate
          safety check -r requirements.txt --ignore mlflow

      - name: Cleanup
        run: |
          deactivate
          rm -rf venv
